version: '3'

services:
  redis:
    image: tibcosoftware/redis:latest
    command: /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes: 
      - ../container_data/redis/data:/data
      - ../container_data/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: on-failure

  insights:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    volumes:
      - ../container_data/redisinsight/import:/import
      - ../container_data/redisinsight/db:/db
    restart: on-failure
    depends_on: 
      - redis

  nginx:
    image: nginx:1.15
    volumes:
      - ../container_data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../container_data/site:/usr/share/nginx/html
      - ../container_data/nginx/discover.cloud.tibco.com.crt:/etc/nginx/discover.cloud.tibco.com.crt 
      - ../container_data/nginx/discover.cloud.tibco.com.key:/etc/nginx/discover.cloud.tibco.com.key
    ports:
      - "80:80"
      - "443:443"
    network_mode: bridge
    restart: on-failure

  discover_dev:
    container_name: discover_dev
    build: 
      context: .
      dockerfile: Dockerfile.development
    command: npm run devDocker
    volumes:
      - .:/usr/tibco-labs/discover
    ports:
      - "8080:8080"
      - "8558:8558"
      - "9229:9229"
    extra_hosts:
      - "orchestrator-service-pub:54.72.206.90"
    networks:
      development_network:
        aliases:
          - analysis-service-pub
          - administration-service-pub
          - datasets-service-pub
          - investigation-service-pub
          - documentation-service-pub
          - templates-service-pub
          - configuration-service-pub
    env_file: 
      - .env
    depends_on:
      - nginx

networks:
  development_network:
  