/**
 * TIBCO Nimbus Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ActivityModelResources {
    'resourceId': number;
    'mapId'?: string;
    'resRefId'?: number;
    'name'?: string;
    'displayName'?: string;
    'infoField1'?: string;
    'infoField2'?: string;
    'status'?: ActivityModelResources.StatusEnum;
    'visible'?: boolean;
    'type'?: ActivityModelResources.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "resourceId",
            "baseName": "resourceId",
            "type": "number"
        },
        {
            "name": "mapId",
            "baseName": "mapId",
            "type": "string"
        },
        {
            "name": "resRefId",
            "baseName": "resRefId",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "infoField1",
            "baseName": "infoField1",
            "type": "string"
        },
        {
            "name": "infoField2",
            "baseName": "infoField2",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ActivityModelResources.StatusEnum"
        },
        {
            "name": "visible",
            "baseName": "visible",
            "type": "boolean"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ActivityModelResources.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return ActivityModelResources.attributeTypeMap;
    }
}

export namespace ActivityModelResources {
    export enum StatusEnum {
        Unknown = <any> 'unknown',
        Central = <any> 'central',
        Local = <any> 'local',
        Override = <any> 'override'
    }
    export enum TypeEnum {
        None = <any> 'none',
        People = <any> 'people',
        System = <any> 'system',
        Other = <any> 'other'
    }
}
