/**
 * TIBCO Nimbus Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DiagramCollectionControlPanelOwner } from './diagramCollectionControlPanelOwner';

export class DiagramCollectionControlPanel {
    'owner'?: DiagramCollectionControlPanelOwner;
    'author'?: DiagramCollectionControlPanelOwner;
    'version': string;
    'title': string;
    'description'?: string;
    'authorizationStatus'?: DiagramCollectionControlPanel.AuthorizationStatusEnum;
    'lockTitle'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "owner",
            "baseName": "owner",
            "type": "DiagramCollectionControlPanelOwner"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "DiagramCollectionControlPanelOwner"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "authorizationStatus",
            "baseName": "authorizationStatus",
            "type": "DiagramCollectionControlPanel.AuthorizationStatusEnum"
        },
        {
            "name": "lockTitle",
            "baseName": "lockTitle",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return DiagramCollectionControlPanel.attributeTypeMap;
    }
}

export namespace DiagramCollectionControlPanel {
    export enum AuthorizationStatusEnum {
        UpdatePending = <any> 'updatePending',
        AuthorizationPending = <any> 'authorizationPending',
        PromotionReady = <any> 'promotionReady',
        DraftLocked = <any> 'draftLocked',
        Authorized = <any> 'authorized'
    }
}
