/**
 * TIBCO Nimbus Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FlowlineModelConnectionsInternalConnections } from './flowlineModelConnectionsInternalConnections';
import { FlowlineModelConnectionsStyle } from './flowlineModelConnectionsStyle';

export class FlowlineModelConnections {
    'externallyConnected'?: boolean;
    'internalConnections'?: Array<FlowlineModelConnectionsInternalConnections>;
    'style'?: FlowlineModelConnectionsStyle;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "externallyConnected",
            "baseName": "externallyConnected",
            "type": "boolean"
        },
        {
            "name": "internalConnections",
            "baseName": "internalConnections",
            "type": "Array<FlowlineModelConnectionsInternalConnections>"
        },
        {
            "name": "style",
            "baseName": "style",
            "type": "FlowlineModelConnectionsStyle"
        }    ];

    static getAttributeTypeMap() {
        return FlowlineModelConnections.attributeTypeMap;
    }
}

