/**
 * TIBCO Nimbus Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityModelBubbleTextText } from './activityModelBubbleTextText';
import { ActivityModelCommentary } from './activityModelCommentary';
import { ActivityModelPosition } from './activityModelPosition';
import { AmxBpmAttachment } from './amxBpmAttachment';
import { DataTableAttachment } from './dataTableAttachment';
import { DiagramAttachment } from './diagramAttachment';
import { DirectFileAttachment } from './directFileAttachment';
import { DocRegistryAttachment } from './docRegistryAttachment';
import { EmailAttachment } from './emailAttachment';
import { ExcelDataLinkAttachment } from './excelDataLinkAttachment';
import { FlowlineModelConnections } from './flowlineModelConnections';
import { FlowlineModelDestObject } from './flowlineModelDestObject';
import { FlowlineModelLinePoints } from './flowlineModelLinePoints';
import { FlowlineModelStyle } from './flowlineModelStyle';
import { FormvineAttachment } from './formvineAttachment';
import { IntImageAttachment } from './intImageAttachment';
import { IntWPAttachment } from './intWPAttachment';
import { MenuFuncAttachment } from './menuFuncAttachment';
import { OracleAttachment } from './oracleAttachment';
import { SAPAttachment } from './sAPAttachment';
import { SalesforceAttachment } from './salesforceAttachment';
import { ScorecardAttachment } from './scorecardAttachment';
import { SpotfireAttachment } from './spotfireAttachment';
import { StoryboardAttachment } from './storyboardAttachment';
import { TibbrAttachment } from './tibbrAttachment';
import { URLAttachment } from './uRLAttachment';

export class FlowlineModel {
    'commentary'?: ActivityModelCommentary;
    'connections'?: FlowlineModelConnections;
    'destObject'?: FlowlineModelDestObject;
    'flowlineId'?: string;
    'linePoints'?: Array<FlowlineModelLinePoints>;
    'sourceObject'?: FlowlineModelDestObject;
    'straight'?: boolean;
    'style'?: FlowlineModelStyle;
    'text'?: ActivityModelBubbleTextText;
    'textPosition'?: ActivityModelPosition;
    'attachments'?: Array<EmailAttachment | TibbrAttachment | ExcelDataLinkAttachment | DataTableAttachment | DirectFileAttachment | AmxBpmAttachment | SAPAttachment | ScorecardAttachment | IntImageAttachment | FormvineAttachment | MenuFuncAttachment | SpotfireAttachment | StoryboardAttachment | IntWPAttachment | DiagramAttachment | SalesforceAttachment | OracleAttachment | DocRegistryAttachment | URLAttachment>;
    'objectId'?: string;
    'position'?: ActivityModelPosition;
    'objectType': FlowlineModel.ObjectTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "commentary",
            "baseName": "commentary",
            "type": "ActivityModelCommentary"
        },
        {
            "name": "connections",
            "baseName": "connections",
            "type": "FlowlineModelConnections"
        },
        {
            "name": "destObject",
            "baseName": "destObject",
            "type": "FlowlineModelDestObject"
        },
        {
            "name": "flowlineId",
            "baseName": "flowlineId",
            "type": "string"
        },
        {
            "name": "linePoints",
            "baseName": "linePoints",
            "type": "Array<FlowlineModelLinePoints>"
        },
        {
            "name": "sourceObject",
            "baseName": "sourceObject",
            "type": "FlowlineModelDestObject"
        },
        {
            "name": "straight",
            "baseName": "straight",
            "type": "boolean"
        },
        {
            "name": "style",
            "baseName": "style",
            "type": "FlowlineModelStyle"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "ActivityModelBubbleTextText"
        },
        {
            "name": "textPosition",
            "baseName": "textPosition",
            "type": "ActivityModelPosition"
        },
        {
            "name": "attachments",
            "baseName": "attachments",
            "type": "Array<EmailAttachment | TibbrAttachment | ExcelDataLinkAttachment | DataTableAttachment | DirectFileAttachment | AmxBpmAttachment | SAPAttachment | ScorecardAttachment | IntImageAttachment | FormvineAttachment | MenuFuncAttachment | SpotfireAttachment | StoryboardAttachment | IntWPAttachment | DiagramAttachment | SalesforceAttachment | OracleAttachment | DocRegistryAttachment | URLAttachment>"
        },
        {
            "name": "objectId",
            "baseName": "objectId",
            "type": "string"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "ActivityModelPosition"
        },
        {
            "name": "objectType",
            "baseName": "objectType",
            "type": "FlowlineModel.ObjectTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return FlowlineModel.attributeTypeMap;
    }
}

export namespace FlowlineModel {
    export enum ObjectTypeEnum {
        Line = <any> 'line'
    }
}
