/**
 * TIBCO Nimbus Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FlowlineModelConnectionsInternalConnections {
    'targetFlowlineId': string;
    'diagramId': string;
    'mapId': string;
    'text'?: string;
    'integrityStatus'?: FlowlineModelConnectionsInternalConnections.IntegrityStatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "targetFlowlineId",
            "baseName": "targetFlowlineId",
            "type": "string"
        },
        {
            "name": "diagramId",
            "baseName": "diagramId",
            "type": "string"
        },
        {
            "name": "mapId",
            "baseName": "mapId",
            "type": "string"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "integrityStatus",
            "baseName": "integrityStatus",
            "type": "FlowlineModelConnectionsInternalConnections.IntegrityStatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return FlowlineModelConnectionsInternalConnections.attributeTypeMap;
    }
}

export namespace FlowlineModelConnectionsInternalConnections {
    export enum IntegrityStatusEnum {
        Ok = <any> 'ok',
        NeedBuild = <any> 'needBuild'
    }
}
