/**
 * TIBCO Nimbus Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MenuFuncAttachment {
    'menuFunctionId'?: number;
    'id'?: string;
    'title'?: string;
    'type'?: MenuFuncAttachment.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "menuFunctionId",
            "baseName": "menuFunctionId",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "MenuFuncAttachment.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return MenuFuncAttachment.attributeTypeMap;
    }
}

export namespace MenuFuncAttachment {
    export enum TypeEnum {
        MenuFunc = <any> 'menuFunc'
    }
}
