/**
 * TIBCO Nimbus Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class StoryboardAttachment {
    'storyboardId'?: number;
    'stepIndex'?: number;
    'id'?: string;
    'title'?: string;
    'type'?: StoryboardAttachment.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "storyboardId",
            "baseName": "storyboardId",
            "type": "number"
        },
        {
            "name": "stepIndex",
            "baseName": "stepIndex",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "StoryboardAttachment.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return StoryboardAttachment.attributeTypeMap;
    }
}

export namespace StoryboardAttachment {
    export enum TypeEnum {
        StoryboardLink = <any> 'storyboardLink'
    }
}
