/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldFormats } from './fieldFormats';
import { Message } from './message';
import { GeneralInformation } from './generalInformation';
import { LandingPage } from './landingPage';
import { Automapping } from './automapping';
import { Analytics } from './analytics';
import { Investigations } from './investigations';


export interface Configuration { 
    general?: GeneralInformation;
    landingPage?: LandingPage;
    messages?: Array<Message>;
    formats?: Array<FieldFormats>;
    automap?: Array<Automapping>;
    investigations?: Investigations;
    analytics?: Analytics;
}

