/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Analytics {
    'previewLocation'?: string;
    'server'?: string;
    'previewTableName'?: string;
    'customUserFolder'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "previewLocation",
            "baseName": "previewLocation",
            "type": "string"
        },
        {
            "name": "server",
            "baseName": "server",
            "type": "string"
        },
        {
            "name": "previewTableName",
            "baseName": "previewTableName",
            "type": "string"
        },
        {
            "name": "customUserFolder",
            "baseName": "customUserFolder",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics.attributeTypeMap;
    }
}

