/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Analytics } from './analytics';
import { Automapping } from './automapping';
import { FieldFormats } from './fieldFormats';
import { GeneralInformation } from './generalInformation';
import { Investigations } from './investigations';
import { LandingPage } from './landingPage';
import { Message } from './message';

export class DiscoverConfiguration {
    'general'?: GeneralInformation;
    'landingPage'?: LandingPage;
    'messages'?: Array<Message>;
    'formats'?: Array<FieldFormats>;
    'automap'?: Array<Automapping>;
    'investigations'?: Investigations;
    'analytics'?: Analytics;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "general",
            "baseName": "general",
            "type": "GeneralInformation"
        },
        {
            "name": "landingPage",
            "baseName": "landingPage",
            "type": "LandingPage"
        },
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<Message>"
        },
        {
            "name": "formats",
            "baseName": "formats",
            "type": "Array<FieldFormats>"
        },
        {
            "name": "automap",
            "baseName": "automap",
            "type": "Array<Automapping>"
        },
        {
            "name": "investigations",
            "baseName": "investigations",
            "type": "Investigations"
        },
        {
            "name": "analytics",
            "baseName": "analytics",
            "type": "Analytics"
        }    ];

    static getAttributeTypeMap() {
        return DiscoverConfiguration.attributeTypeMap;
    }
}

