/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InvestigationTriggerAttributes } from './investigationTriggerAttributes';

export class InvestigationTrigger {
    'label'?: string;
    'value'?: string;
    'fields'?: Array<InvestigationTriggerAttributes>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<InvestigationTriggerAttributes>"
        }    ];

    static getAttributeTypeMap() {
        return InvestigationTrigger.attributeTypeMap;
    }
}

