/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InvestigationCreateRequest {
    'type'?: string;
    'ids'?: string;
    'details'?: string;
    'summary'?: string;
    'analysisId'?: string;
    'analysisName'?: string;
    'templateId'?: string;
    'templateName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "ids",
            "baseName": "ids",
            "type": "string"
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "string"
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string"
        },
        {
            "name": "analysisId",
            "baseName": "analysisId",
            "type": "string"
        },
        {
            "name": "analysisName",
            "baseName": "analysisName",
            "type": "string"
        },
        {
            "name": "templateId",
            "baseName": "templateId",
            "type": "string"
        },
        {
            "name": "templateName",
            "baseName": "templateName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InvestigationCreateRequest.attributeTypeMap;
    }
}

