/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MapFolderModelAccessRightsSpecific {
    'id'?: number;
    'type'?: MapFolderModelAccessRightsSpecific.TypeEnum;
    'access'?: MapFolderModelAccessRightsSpecific.AccessEnum;
    'name'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "MapFolderModelAccessRightsSpecific.TypeEnum"
        },
        {
            "name": "access",
            "baseName": "access",
            "type": "MapFolderModelAccessRightsSpecific.AccessEnum"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MapFolderModelAccessRightsSpecific.attributeTypeMap;
    }
}

export namespace MapFolderModelAccessRightsSpecific {
    export enum TypeEnum {
        User = <any> 'user',
        Group = <any> 'group'
    }
    export enum AccessEnum {
        Allowed = <any> 'allowed',
        Denied = <any> 'denied'
    }
}
