/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MapFolderCollectionBreadcrumbs } from './mapFolderCollectionBreadcrumbs';
import { MapFolderModel } from './mapFolderModel';

export class MapFolderCollection {
    'items'?: Array<MapFolderModel>;
    'breadcrumbs'?: Array<MapFolderCollectionBreadcrumbs>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<MapFolderModel>"
        },
        {
            "name": "breadcrumbs",
            "baseName": "breadcrumbs",
            "type": "Array<MapFolderCollectionBreadcrumbs>"
        }    ];

    static getAttributeTypeMap() {
        return MapFolderCollection.attributeTypeMap;
    }
}

