/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The copy of the backend redisFileInfo model. See https://discover.labs.tibcocloud.com/backswagger#/Files%20Operations/getRouteFileV2
*/
export class RedisFileInfo {
    'ContentType': string;
    'LastModified': string;
    'OriginalFilename': string;
    'OriginalEncoding': string;
    'FileSize': string;
    'newline': string;
    'EscapeChar': string;
    'QuoteChar': string;
    'Separator': string;
    'Encoding': string;
    'OriginalNewLine': string;
    'FileLocation': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ContentType",
            "baseName": "ContentType",
            "type": "string"
        },
        {
            "name": "LastModified",
            "baseName": "LastModified",
            "type": "string"
        },
        {
            "name": "OriginalFilename",
            "baseName": "OriginalFilename",
            "type": "string"
        },
        {
            "name": "OriginalEncoding",
            "baseName": "OriginalEncoding",
            "type": "string"
        },
        {
            "name": "FileSize",
            "baseName": "FileSize",
            "type": "string"
        },
        {
            "name": "newline",
            "baseName": "newline",
            "type": "string"
        },
        {
            "name": "EscapeChar",
            "baseName": "EscapeChar",
            "type": "string"
        },
        {
            "name": "QuoteChar",
            "baseName": "QuoteChar",
            "type": "string"
        },
        {
            "name": "Separator",
            "baseName": "Separator",
            "type": "string"
        },
        {
            "name": "Encoding",
            "baseName": "Encoding",
            "type": "string"
        },
        {
            "name": "OriginalNewLine",
            "baseName": "OriginalNewLine",
            "type": "string"
        },
        {
            "name": "FileLocation",
            "baseName": "FileLocation",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RedisFileInfo.attributeTypeMap;
    }
}

