/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NewVisualisationInformation } from './newVisualisationInformation';
import { Template } from './template';

export class TemplateRequest {
    'template': Template;
    'visualisation'?: NewVisualisationInformation;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "template",
            "baseName": "template",
            "type": "Template"
        },
        {
            "name": "visualisation",
            "baseName": "visualisation",
            "type": "NewVisualisationInformation"
        }    ];

    static getAttributeTypeMap() {
        return TemplateRequest.attributeTypeMap;
    }
}

