/**
 * TIBCO Nimbus Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ActivityModelStatementLinks {
    'linkId'?: number;
    'statementId'?: number;
    'statementName'?: string;
    'setName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "linkId",
            "baseName": "linkId",
            "type": "number"
        },
        {
            "name": "statementId",
            "baseName": "statementId",
            "type": "number"
        },
        {
            "name": "statementName",
            "baseName": "statementName",
            "type": "string"
        },
        {
            "name": "setName",
            "baseName": "setName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ActivityModelStatementLinks.attributeTypeMap;
    }
}

