/**
 * TIBCO Nimbus Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ActivityModelDiagramLink {
    'targetMapId': string;
    'targetDiagramId': string;
    'isValid'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "targetMapId",
            "baseName": "targetMapId",
            "type": "string"
        },
        {
            "name": "targetDiagramId",
            "baseName": "targetDiagramId",
            "type": "string"
        },
        {
            "name": "isValid",
            "baseName": "isValid",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ActivityModelDiagramLink.attributeTypeMap;
    }
}

