/**
 * TIBCO Nimbus Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityModel } from './activityModel';
import { DiagramModelControlPanel } from './diagramModelControlPanel';
import { DiagramModelLanguage } from './diagramModelLanguage';
import { FlowlineModel } from './flowlineModel';
import { ImageBoxModel } from './imageBoxModel';
import { TextboxModel } from './textboxModel';

export class DiagramModel {
    'controlPanel'?: DiagramModelControlPanel;
    'diagramId'?: string;
    'language': DiagramModelLanguage;
    'level'?: string;
    'mode'?: DiagramModel.ModeEnum;
    'objects'?: Array<ActivityModel | ImageBoxModel | TextboxModel | FlowlineModel>;
    'parentObjectId'?: string;
    'parentDiagramId'?: string;
    'revision'?: number;
    'themed'?: boolean;
    'width'?: number;
    'height'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "controlPanel",
            "baseName": "controlPanel",
            "type": "DiagramModelControlPanel"
        },
        {
            "name": "diagramId",
            "baseName": "diagramId",
            "type": "string"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "DiagramModelLanguage"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "string"
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "DiagramModel.ModeEnum"
        },
        {
            "name": "objects",
            "baseName": "objects",
            "type": "Array<ActivityModel | ImageBoxModel | TextboxModel | FlowlineModel>"
        },
        {
            "name": "parentObjectId",
            "baseName": "parentObjectId",
            "type": "string"
        },
        {
            "name": "parentDiagramId",
            "baseName": "parentDiagramId",
            "type": "string"
        },
        {
            "name": "revision",
            "baseName": "revision",
            "type": "number"
        },
        {
            "name": "themed",
            "baseName": "themed",
            "type": "boolean"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DiagramModel.attributeTypeMap;
    }
}

export namespace DiagramModel {
    export enum ModeEnum {
        Classic = <any> 'classic',
        Modern = <any> 'modern'
    }
}
