/**
 * TIBCO Nimbus Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FlowlineModelDestObject {
    'objectId'?: string;
    'objectDisplayId'?: number;
    'edge'?: FlowlineModelDestObject.EdgeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "objectId",
            "baseName": "objectId",
            "type": "string"
        },
        {
            "name": "objectDisplayId",
            "baseName": "objectDisplayId",
            "type": "number"
        },
        {
            "name": "edge",
            "baseName": "edge",
            "type": "FlowlineModelDestObject.EdgeEnum"
        }    ];

    static getAttributeTypeMap() {
        return FlowlineModelDestObject.attributeTypeMap;
    }
}

export namespace FlowlineModelDestObject {
    export enum EdgeEnum {
        None = <any> 'none',
        Left = <any> 'left',
        Top = <any> 'top',
        Right = <any> 'right',
        Bottom = <any> 'bottom'
    }
}
