/**
 * TIBCO Nimbus Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FlowlineModelConnectionsStyle {
    'displaySize'?: number;
    'displayAtEnd'?: boolean;
    'visible'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "displaySize",
            "baseName": "displaySize",
            "type": "number"
        },
        {
            "name": "displayAtEnd",
            "baseName": "displayAtEnd",
            "type": "boolean"
        },
        {
            "name": "visible",
            "baseName": "visible",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return FlowlineModelConnectionsStyle.attributeTypeMap;
    }
}

