CREATE USER user_ro WITH PASSWORD '';
GRANT CONNECT ON DATABASE discover_demo TO user_ro;
GRANT USAGE ON SCHEMA demo TO user_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA demo TO user_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA demo GRANT SELECT ON TABLES TO user_ro;

CREATE USER user_rw WITH PASSWORD '';
GRANT CONNECT ON DATABASE discover_demo TO demo_rw;
GRANT USAGE, CREATE ON SCHEMA demo TO user_rw;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA demo TO user_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA demo GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO user_rw;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA demo TO user_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA demo GRANT USAGE ON SEQUENCES TO user_rw;