ALTER DEFAULT PRIVILEGES IN SCHEMA my_schema REVOKE ALL PRIVILEGES ON TABLES FROM  my_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA my_schema REVOKE ALL PRIVILEGES ON SEQUENCES FROM my_user;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA my_schema FROM my_user;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA my_schema FROM my_user;

REVOKE ALL ON SCHEMA my_schema FROM my_user;

REVOKE CONNECT ON DATABASE my_database FROM my_user;

DROP USER my_user;