/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FasIconPicker {
        "name": string;
        "value": string;
    }
    interface KpiCard {
        /**
          * The icon
         */
        "icon": string;
        /**
          * The first name
         */
        "name": string;
        /**
          * The value
         */
        "value": string;
    }
    interface KpiChart {
        /**
          * TODO :
         */
        "data": string;
    }
    interface KpiConfig {
        "cards": Array<{
            name: string;
            value: string;
            icon: string;
        }>;
        "open": boolean;
        "transparent": boolean;
    }
}
declare global {
    interface HTMLFasIconPickerElement extends Components.FasIconPicker, HTMLStencilElement {
    }
    var HTMLFasIconPickerElement: {
        prototype: HTMLFasIconPickerElement;
        new (): HTMLFasIconPickerElement;
    };
    interface HTMLKpiCardElement extends Components.KpiCard, HTMLStencilElement {
    }
    var HTMLKpiCardElement: {
        prototype: HTMLKpiCardElement;
        new (): HTMLKpiCardElement;
    };
    interface HTMLKpiChartElement extends Components.KpiChart, HTMLStencilElement {
    }
    var HTMLKpiChartElement: {
        prototype: HTMLKpiChartElement;
        new (): HTMLKpiChartElement;
    };
    interface HTMLKpiConfigElement extends Components.KpiConfig, HTMLStencilElement {
    }
    var HTMLKpiConfigElement: {
        prototype: HTMLKpiConfigElement;
        new (): HTMLKpiConfigElement;
    };
    interface HTMLElementTagNameMap {
        "fas-icon-picker": HTMLFasIconPickerElement;
        "kpi-card": HTMLKpiCardElement;
        "kpi-chart": HTMLKpiChartElement;
        "kpi-config": HTMLKpiConfigElement;
    }
}
declare namespace LocalJSX {
    interface FasIconPicker {
        "name"?: string;
        "value"?: string;
    }
    interface KpiCard {
        /**
          * The icon
         */
        "icon"?: string;
        /**
          * The first name
         */
        "name"?: string;
        /**
          * The value
         */
        "value"?: string;
    }
    interface KpiChart {
        /**
          * TODO :
         */
        "data"?: string;
        "onConfigSaved"?: (event: CustomEvent<{
            mapping: Array<{
                name: string;
                icon: string;
            }>;
        }>) => void;
    }
    interface KpiConfig {
        "cards"?: Array<{
            name: string;
            value: string;
            icon: string;
        }>;
        "onConfigSaved"?: (event: CustomEvent<{
            mapping: Array<{
                name: string;
                icon: string;
            }>;
        }>) => void;
        "open"?: boolean;
        "transparent"?: boolean;
    }
    interface IntrinsicElements {
        "fas-icon-picker": FasIconPicker;
        "kpi-card": KpiCard;
        "kpi-chart": KpiChart;
        "kpi-config": KpiConfig;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fas-icon-picker": LocalJSX.FasIconPicker & JSXBase.HTMLAttributes<HTMLFasIconPickerElement>;
            "kpi-card": LocalJSX.KpiCard & JSXBase.HTMLAttributes<HTMLKpiCardElement>;
            "kpi-chart": LocalJSX.KpiChart & JSXBase.HTMLAttributes<HTMLKpiChartElement>;
            "kpi-config": LocalJSX.KpiConfig & JSXBase.HTMLAttributes<HTMLKpiConfigElement>;
        }
    }
}
