/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MapFolderModelAccessRightsSpecific { 
    id?: number;
    type?: MapFolderModelAccessRightsSpecific.TypeEnum;
    access?: MapFolderModelAccessRightsSpecific.AccessEnum;
    readonly name?: string;
}
export namespace MapFolderModelAccessRightsSpecific {
    export type TypeEnum = 'user' | 'group';
    export const TypeEnum = {
        User: 'user' as TypeEnum,
        Group: 'group' as TypeEnum
    };
    export type AccessEnum = 'allowed' | 'denied';
    export const AccessEnum = {
        Allowed: 'allowed' as AccessEnum,
        Denied: 'denied' as AccessEnum
    };
}


