/**
 * TIBCO DISCOVER backend microservice
 * Api Layer for the backend of Project Discover
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fcenedes@tibco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ListBucket {
    'bucketName': string;
    'key': string;
    'eTag': string;
    'size': number;
    'lastModified': string;
    'storageClass': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bucketName",
            "baseName": "bucketName",
            "type": "string"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "eTag",
            "baseName": "eTag",
            "type": "string"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "lastModified",
            "baseName": "lastModified",
            "type": "string"
        },
        {
            "name": "storageClass",
            "baseName": "storageClass",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ListBucket.attributeTypeMap;
    }
}

