/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RangeSlider {
        "max": number;
        "min": number;
        "orientation": string;
        "showTooltip": boolean;
        "step": number;
        "value": number;
    }
}
declare global {
    interface HTMLRangeSliderElement extends Components.RangeSlider, HTMLStencilElement {
    }
    var HTMLRangeSliderElement: {
        prototype: HTMLRangeSliderElement;
        new (): HTMLRangeSliderElement;
    };
    interface HTMLElementTagNameMap {
        "range-slider": HTMLRangeSliderElement;
    }
}
declare namespace LocalJSX {
    interface RangeSlider {
        "max"?: number;
        "min"?: number;
        "onSliderUpdate"?: (event: CustomEvent<{
            value: number;
        }>) => void;
        "orientation"?: string;
        "showTooltip"?: boolean;
        "step"?: number;
        "value"?: number;
    }
    interface IntrinsicElements {
        "range-slider": RangeSlider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "range-slider": LocalJSX.RangeSlider & JSXBase.HTMLAttributes<HTMLRangeSliderElement>;
        }
    }
}
