#
# Copyright 2020 TIBCO Software Inc.
#
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pm
  namespace: spark-operator
spec:
  type: Scala
  mode: cluster
  image: "tibcosoftware/labs-discover-spark-pm:latest"
  imagePullPolicy: Always
  imagePullSecrets:
    - regcred
  mainClass: com.tibco.labs.main
  mainApplicationFile: "local:///opt/spark/jars/tibcosoftware-labs-discover-spark-pm.jar"
  arguments:
    - "DIS_000014"
    - "discover"
  sparkVersion: "2.4.5"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    env:
      - name: liveAppClientId
        valueFrom:
            secretKeyRef:
                name: liveapps
                key: liveAppClientId
      - name: liveAppEmail
        valueFrom:
            secretKeyRef:
                name: liveapps
                key: liveAppEmail
      - name: liveAppPassword
        valueFrom:
            secretKeyRef:
                name: liveapps
                key: liveAppPassword
    cores: 1
    coreLimit: "1200m"
    memory: "1024m"
    labels:
      version: 2.4.5
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "1024m"
    labels:
      version: 2.4.5
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"