/**
 * TIBCO DISCOVER backend microservice
 * Api Layer for the backend of Project Discover
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fcenedes@tibco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AnalysisMetrics } from './analysisMetrics';

export class MetricsAnalysis {
    'Organisation': string;
    'jobName': string;
    'analysisID': string;
    'Metrics': AnalysisMetrics;
    'durationDB': number;
    'durationJob': number;
    'timeStamp': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "Organisation",
            "baseName": "Organisation",
            "type": "string"
        },
        {
            "name": "jobName",
            "baseName": "jobName",
            "type": "string"
        },
        {
            "name": "analysisID",
            "baseName": "analysisID",
            "type": "string"
        },
        {
            "name": "Metrics",
            "baseName": "Metrics",
            "type": "AnalysisMetrics"
        },
        {
            "name": "durationDB",
            "baseName": "durationDB",
            "type": "number"
        },
        {
            "name": "durationJob",
            "baseName": "durationJob",
            "type": "number"
        },
        {
            "name": "timeStamp",
            "baseName": "timeStamp",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return MetricsAnalysis.attributeTypeMap;
    }
}

