/**
 * TIBCO DISCOVER backend microservice
 * Api Layer for the backend of Project Discover
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fcenedes@tibco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DatasetSource } from './datasetSource';
import { Filter } from './filter';
import { Mapping } from './mapping';
import { Schedule } from './schedule';
import { Schema } from './schema';

export class PmConfigLiveApps {
    'schema': Array<Schema>;
    'datasetSource': DatasetSource;
    'filters'?: Array<Filter>;
    'groups'?: Array<Filter>;
    'id': string;
    'version': string;
    'token': string;
    'mappings': Mapping;
    'organization': string;
    'schedule'?: Schedule;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "schema",
            "baseName": "schema",
            "type": "Array<Schema>"
        },
        {
            "name": "datasetSource",
            "baseName": "datasetSource",
            "type": "DatasetSource"
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "Array<Filter>"
        },
        {
            "name": "groups",
            "baseName": "groups",
            "type": "Array<Filter>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        },
        {
            "name": "mappings",
            "baseName": "mappings",
            "type": "Mapping"
        },
        {
            "name": "organization",
            "baseName": "organization",
            "type": "string"
        },
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "Schedule"
        }    ];

    static getAttributeTypeMap() {
        return PmConfigLiveApps.attributeTypeMap;
    }
}

