/**
 * TIBCO DISCOVER backend microservice
 * Api Layer for the backend of Project Discover
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fcenedes@tibco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SchemaPreview } from './schemaPreview';

export class PreviewConfigFile {
    'Token': string;
    'Organization': string;
    'DatasetId': string;
    'schema'?: Array<SchemaPreview>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "Token",
            "baseName": "Token",
            "type": "string"
        },
        {
            "name": "Organization",
            "baseName": "Organization",
            "type": "string"
        },
        {
            "name": "DatasetId",
            "baseName": "DatasetId",
            "type": "string"
        },
        {
            "name": "schema",
            "baseName": "schema",
            "type": "Array<SchemaPreview>"
        }    ];

    static getAttributeTypeMap() {
        return PreviewConfigFile.attributeTypeMap;
    }
}

