/**
 * TIBCO DISCOVER backend microservice
 * Api Layer for the backend of Project Discover
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fcenedes@tibco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Schema {
    'format': string;
    'ColumnName': string;
    'DataType': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "format",
            "baseName": "format",
            "type": "string"
        },
        {
            "name": "ColumnName",
            "baseName": "ColumnName",
            "type": "string"
        },
        {
            "name": "DataType",
            "baseName": "DataType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Schema.attributeTypeMap;
    }
}

